"""Assemble the audit and action plan from measured evidence and explicit judgments."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
S = json.loads((ROOT / "data/gsc/summary.json").read_text(encoding="utf-8"))
C = json.loads((ROOT / "data/crawl.json").read_text(encoding="utf-8"))
categories = [
    {"name": "Technical SEO", "weight": 22, "score": 88, "basis": "All 49 canonical pages accessible, self-canonical and allowed; malformed image sitemap and one orphan remain."},
    {"name": "Content Quality", "weight": 23, "score": 53, "basis": "Useful tools and guidance, undermined by demonstrated format defects and unsupported product/platform claims."},
    {"name": "On-Page SEO", "weight": 20, "score": 65, "basis": "Distinct titles, H1s and readable server HTML; action-oriented landing pages add an unconfigured extra step and important intent answers are missing."},
    {"name": "Schema / Structured Data", "weight": 10, "score": 70, "basis": "Parseable JSON-LD and breadcrumbs; page-function and author-entity mismatches remain."},
    {"name": "Performance (lab only)", "weight": 10, "score": 64, "basis": "Mobile Lighthouse64, LCP3.96s/TBT529ms; desktop CLS0.212. Field CWV/INP unavailable, so this category is provisional."},
    {"name": "AI Search Readiness", "weight": 10, "score": 80, "basis": "Readable HTML and crawler access; source accuracy, attribution and optional llms formatting need work. Visibility unmeasured."},
    {"name": "Images", "weight": 5, "score": 78, "basis": "All15 sampled assets valid and small; invalid image sitemap and absent original explanatory visuals."},
]
score = round(sum(c["weight"] * c["score"] for c in categories) / 100)
actions = [
    {"id": "A1", "priority": "High", "title": "Make advertised converter outputs valid", "observation": "Live AVIF and BMP downloads contain PNG bytes and MIME despite .avif/.bmp filenames. See tool-quality.md for other decoder results.", "recommendation": "Use verified encoders or disable unsupported outputs with a clear message. Confirm MIME and extension from the actual encoded blob, then align all conversion landing-page claims.", "depends_on": "None; before promoting converters or linking the orphan AVIF page.", "acceptance": "For each advertised format, a known input exports a matching signature/MIME/extension and decodes in two independent readers. Transparency/dimensions follow documented behavior.", "failed_if": "Any advertised output is mislabeled, fails decoding, or becomes a silent PNG fallback.", "indicator": "Format regression pass rate and conversion error reports.", "effort": "1-3 days, longer if new encoders are needed"},
    {"id": "A2", "priority": "High", "title": "Correct compressor state and target-size behavior", "observation": "Changing a completed JPEG job to WebP can leave a JPEG download. Source repeats the same midpoint quality asynchronously; live copy promises exact size/lossless PNG.", "recommendation": "Invalidate results when settings change; make quality search sequential; disclose dimension changes and impossible targets. Remove lossless PNG claims unless implemented.", "depends_on": "None; review code and visible claims together.", "acceptance": "Recompressing after a format/quality/target change produces the new requested result. Output is at/below the target or clearly reports failure, with resulting dimensions and transparency shown.", "failed_if": "Old bytes remain after changed settings, target is exceeded without warning, or PNG is silently represented as lossless while transcoded.", "indicator": "Changed-setting and target-size regression results, successful download rate.", "effort": "1-2 days"},
    {"id": "A3", "priority": "High", "title": "Restore narrow-screen usability and reduce page instability", "observation": "375px tests show document overflow to523px on converter and382px on home. Mobile supplies69.2% of search clicks; desktop lab CLS is0.212.", "recommendation": "Fix header/control min-width and wrapping, improve title letter spacing, reserve widget space, and investigate the third-party StartupBar cost before removing or deferring it.", "depends_on": "Capture comparable screenshots and traces first; verify any widget change preserves intended business behavior.", "acceptance": "At320,375,390,768px the document has no unintended horizontal overflow; upload/export/nav controls remain visible and operable. Repeated lab runs show reduced layout shift and no lost functions.", "failed_if": "Menus/download controls still clip or layout shifts persist after the suspected cause is changed.", "indicator": "Viewport regression checks, CLS/LCP lab median, eventual mobile CrUX p75.", "effort": "1-3 days"},
    {"id": "A4", "priority": "High", "title": "Publish the verified existing fixes through a controlled release", "observation": "Local branch has substantial prepared SEO changes while live sitemap XML, copy and CSP still show old behavior.", "recommendation": "Review existing diffs rather than rewriting them. Revalidate the current Next.js build and release bundle, including new tool fixes, then verify production output.", "depends_on": "Review A1-A3 and existing local changes; pass appropriate build/browser/SEO checks before deployment.", "acceptance": "Live image sitemap parses, current metadata/copy is present, relevant analytics requests succeed, new guide resolves200 and legacy article redirects permanently to it, with no tool regression.", "failed_if": "Source checks pass but public URLs retain old behavior, or the release regresses exports/presets.", "indicator": "Public smoke checks and deployment commit identification.", "effort": "Half to one day after release candidate is ready"},
    {"id": "A5", "priority": "High", "title": "Optimize the square-maker cluster around demonstrated output", "observation": "Home contributes382 clicks/21,085 impressions. 'square image' has2,309 impressions at9.12 with10 clicks; 'make image square'1,003 impressions at7.72 with3 clicks.", "recommendation": "Keep the homepage as the working tool. Explain fit/pad versus crop clearly; show a real before/after and export dimensions. Publish the prepared worked-example guide for instructional intent and link both ways.", "depends_on": "A3/A4; use tested tool output for illustrations.", "acceptance": "Tool keeps the whole photo in pad modes, crop loss is disclosed, one clear primary H1/title matches the task, guide/tool links and old-URL redirect work.", "failed_if": "After recrawl and28 complete days the comparable non-branded query cohort fails to improve clicks/CTR and users still abandon the task; investigate competing results and completion friction.", "indicator": "Same-query clicks/CTR by device, tool-to-download completion, guide-to-tool use.", "effort": "1-2 days; much copy already prepared"},
    {"id": "A6", "priority": "High", "title": "Complete the calculator and qualify upscaler promises", "observation": "Calculator12 clicks/2,378 impressions; live tool mainly matches preset dimensions. Upscaler28 clicks, with relevant PNG/non-AI query leads but unsupported GPU/bicubic/detail-recovery claims.", "recommendation": "Release the prepared ratio/megapixel/proportional-resize functions and honest smoothing/sharpening copy after verifying boundaries and downloads. Add useful examples and transparency limits.", "depends_on": "A4 and functional QA; do not claim an AI model or recovered detail.", "acceptance": "1200x800 reports3:2,0.96MP and1080x720 at proportional1080 width. Invalid values produce clear feedback. Upscale output dimensions match2x/3x/4x and documented alpha/format behavior.", "failed_if": "Calculator outputs are wrong or the upscaler still implies unsupported detail reconstruction; search uplift without successful results is insufficient.", "indicator": "Task regression checks and relevant calculator/PNG-upscaler query clicks.", "effort": "Half to one day; substantial local fixes exist"},
    {"id": "A7", "priority": "Medium", "title": "Give platform/conversion landing pages a configured action", "observation": "13 resizer pages are guide/CTA pages. Action-oriented converter URLs likewise send users elsewhere without retaining the selected pair.", "recommendation": "Embed the working tool or pass and apply platform, preset, input/output selection into it. Make WebApplication schema agree with what is available on the URL.", "depends_on": "A1/A2 for conversion/compression and verified presets; avoid claiming a tool before it works.", "acceptance": "A visitor arriving on LinkedIn, Instagram, Discord or PNG-to-AVIF can complete the named task without reselecting it. Browser back/forward and preset state behave correctly.", "failed_if": "CTA returns to a generic tool and loses the promised task, or schema still describes absent functionality.", "indicator": "Landing-to-upload/download completion and task-state regression checks.", "effort": "2-4 days across shared templates"},
    {"id": "A8", "priority": "Medium", "title": "Review platform guides against current official sources", "observation": "Reels guide12 clicks/1,964 impressions; queries ask whether Reels and Stories share a size. Guide tables/limits lack clear primary-source links and original visual evidence.", "recommendation": "Answer the shared9:16-canvas question first, distinguish image artwork from video requirements, date verified official references, and add original crop/safe-zone examples. Prioritize Reels, LinkedIn and Instagram, then Discord.", "depends_on": "A4/A7; verify fast-changing requirements before stating them as facts.", "acceptance": "Every material platform limit has a dated official citation or is qualified as a recommendation; examples match actual presets and display-crop behavior.", "failed_if": "Official references contradict page statements or equivalent query clicks and guide-to-tool use stagnate after a sufficiently sized comparison.", "indicator": "Specification review checklist, guide query cohorts, relevant tool referrals.", "effort": "1-2 days per priority cluster"},
    {"id": "A9", "priority": "Medium", "title": "Investigate cropper indexing and repair contextual links", "observation": "Google reports cropper discovered-currently not indexed, while9 other sampled existing pages are indexed. WebP-to-AVIF is sitemap-only in the raw anchor graph.", "recommendation": "Improve cropper task quality and contextual placement, then inspect after recrawl. Link the orphan conversion page only after AVIF works. Do not create duplicate keyword URLs or submit ordinary tools to Google's restricted Indexing API.", "depends_on": "A1/A3 and improved relevant tool content.", "acceptance": "Target pages are reachable in relevant HTML anchors, return200/self-canonical/no-noindex, and URL Inspection is rechecked after Google crawls them.", "failed_if": "Pages remain uncrawled/excluded after meaningful quality/link changes; investigate exact coverage signals rather than assuming a sitemap guarantees inclusion.", "indicator": "Last-crawl timestamp, coverage state and useful query impressions.", "effort": "Half to one day plus crawl latency"},
    {"id": "A10", "priority": "Medium", "title": "Align authorship, privacy claims and social previews", "observation": "SevenOneLabs is typed both Person and Organization; llms says no tracking despite analytics;35/49 pages lack OG images.", "recommendation": "Use truthful author/reviewer identities and consistent schema IDs; distinguish local image processing from analytics; reuse validated share assets on missing templates. Optional llms Markdown cleanup comes afterwards.", "depends_on": "Verify actual network/consent behavior; coordinate shared metadata/entity templates.", "acceptance": "Author types agree across profile/guides, privacy statements match measured behavior, and intended pages emit a valid relevant share image with alt text.", "failed_if": "Identity/claim contradictions remain or share scrapers cannot retrieve the declared image.", "indicator": "Entity/claim checks, share-preview coverage and support reports.", "effort": "1 day; several local fixes already prepared"},
    {"id": "A11", "priority": "Medium", "title": "Measure successful tool use alongside search traffic", "observation": "GSC is connected but GA4 property/conversion data are unavailable. Source event tracking covers the shared square editor and does not establish completion events for every standalone tool; live CSP blocks some analytics requests.", "recommendation": "Repair/verify collection, then record upload accepted, processing success/error and download for each tool with consistent event labels and applicable consent behavior. Keep page/query/device baselines and record deployment dates.", "depends_on": "A1-A4; verified analytics access required to report actual conversions.", "acceptance": "Each test workflow produces one correctly labeled completion or error event; no private image content/file names are sent. Compare28 complete post-release days after recrawl with this baseline.", "failed_if": "Events duplicate, disappear or count a mislabeled/corrupt file as success, or changes cannot be tied to a recorded deployment.", "indicator": "Event QA, successful-download rate and GSC same-cohort clicks.", "effort": "1-2 days plus measurement window"},
]
actions.insert(2, {"id": "A12", "priority": "High", "title": "Export crop selections in the intended source dimensions", "observation": "A 600 x 400 source exported as 560 x 560 by default and 700 x 394 in 16:9. The output uses the displayed crop rectangle size, with source-coordinate scaling handled separately.", "recommendation": "Map the selected rectangle into source-image coordinates, constrain bounds, and distinguish cropping from intentional resizing. Show resulting export dimensions before download.", "depends_on": "Before A4 release and before treating cropper quality as resolved in A9.", "acceptance": "Known marked test images crop to the selected source region without unintended blank space, stretching or enlargement. Export dimensions match the documented mode on desktop and mobile.", "failed_if": "Display size still controls an undocumented output resize or selected content/bounds differ from the download.", "indicator": "Source-region and dimension regression checks; crop-related error reports.", "effort": "1-2 days"})
findings = [
    {"title": a["title"], "severity": a["priority"], "description": a["observation"], "recommendation": a["recommendation"]}
    for a in actions
]
envelope = {"summary": {"health_score": score, "score_type": "Provisional editorial audit score; not a Google score or field CWV grade",
    "business_type": "Free browser-based image editing tools with informational guides",
    "date": "2026-10-08", "canonical_origin": "https://www.squarepic.io", "pages_audited": 49,
    "top_findings": [a["observation"] for a in actions[:5]], "quick_wins": ["Review and release already prepared fixes.", "Repair image sitemap XML.", "Correct misleading product claims.", "Reuse validated social previews.", "Improve high-traffic homepage clarity."]},
    "categories": categories,
    "findings": findings,
    "action_plan": {"phases": [
        {"name": "Product correctness and mobile usability", "timeframe": "Week1", "items": [a for a in actions if a["id"] in ["A1","A2","A3","A12"]]},
        {"name": "Release and priority intent improvements", "timeframe": "Weeks1-2", "items": [a for a in actions if a["id"] in ["A4","A5","A6","A7"]]},
        {"name": "Evidence, indexing and measurement", "timeframe": "Weeks2-3", "items": [a for a in actions if a["id"] in ["A8","A9","A10","A11"]]},
        {"name": "Measure after release and recrawl", "timeframe": "After28 complete days", "items": ["Compare identical page/query cohorts by device and country. Recheck stored indexing and repeat representative export tests."]}]},
    "gsc": S,
    "limitations": ["Field CWV/INP unavailable; PSI quota429.", "11 indexing inspections only, not a sitewide index count.", "Representative tool tests in Chromium, not every format/browser/input.", "No GA4 conversion data, controlled Google SERP overlap or complete backlink profile.", "Application code unchanged during this audit; existing local fixes remain pending deployment."],
    "artifacts": {"findings_dir": "findings/", "screenshots_dir": "screenshots/", "data_dir": "data/"}}
category_actions = {"Technical SEO": ["A4", "A9"], "Content Quality": ["A1", "A2", "A12", "A6", "A8"],
                    "On-Page SEO": ["A5", "A7"], "Schema / Structured Data": ["A7", "A10"],
                    "Performance (lab only)": ["A3"], "AI Search Readiness": ["A8", "A10"], "Images": ["A4", "A10"]}
for category in envelope["categories"]:
    category["findings"] = [{"title": a["title"], "severity": a["priority"],
                              "description": a["observation"], "recommendation": a["recommendation"]}
                             for a in actions if a["id"] in category_actions[category["name"]]]
envelope["detailed_actions"] = actions
for phase in envelope["action_plan"]["phases"]:
    phase["items"] = [f"{a['id']}: {a['title']}. {a['recommendation']}" if isinstance(a, dict) else a for a in phase["items"]]
(ROOT / "audit-data.json").write_text(json.dumps(envelope, indent=2), encoding="utf-8")

lines = ["# SquarePic full-site SEO and tool-quality audit", "", "8 October 2026, Asia/Calcutta. Live site [squarepic.io](https://squarepic.io/) redirects to the production origin [www.squarepic.io](https://www.squarepic.io/).",
    "", f"Provisional SEO health score: **{score}/100**. This is a weighted editorial assessment of the observed site, not a Google score, a ranking forecast, a compliance certification or a field Core Web Vitals result. Tool failures affect content quality because the tool is the main content of a utility page. The expanded scope and fresh tests make this unsuitable as a before/after comparison with earlier audit scores.",
    "", "The immediate opportunity is to improve the pages already earning traffic while making their tools dependable. The homepage dominates search clicks. Adding more keyword pages before fixing downloads, mobile layout and task continuity would expose more people to incomplete promises.",
    "", "## Scope and evidence", "", "All49 main-sitemap canonical pages were fetched, plus one redirect alias. Robots rules were respected, the crawl queue was exhausted below the500-page cap, and the main/image sitemaps, internal anchor graph, metadata, headings, JSON-LD and sample assets were inspected. Nine guides and shared platform/conversion templates were reviewed. Desktop/mobile browser screenshots and representative real upload-to-download workflows supplement the raw crawl.",
    "", "Search Console was accessed successfully through existing read-only credentials for `sc-domain:squarepic.io`. Fresh page/query/device/country/date data and11 stored URL inspections are saved. Current dates are8 September to5 October; previous dates11 August to7 September; support window8 July to5 October2026. These are Pacific reporting dates, with28 complete days in both comparison windows.",
    "", "Application code, production configuration and existing local edits were not changed. The earlier `docs/seo-audit` and `docs/gsc-2026-10-07` reports were treated as history, not proof of current production behavior. New files are confined to this audit directory.",
    "", "## Search performance and priorities", "", "| Metric | Previous28 days | Current28 days | Change |", "| --- | ---: | ---: | ---: |",
    "| Clicks |309|461|+49.2%|", "| Impressions |21,843|28,926|+32.4%|", "| CTR |1.41%|1.59%|+0.18percentage points|", "| Average position |24.00|8.97|15.04positions lower numerically|",
    "", "This improvement predates this audit and is not attributed to local edits, a Google update or a particular optimization. Average position changes with query mix. Site totals use separate dimensionless requests; page/query rows are not interchangeable with property totals. [Google explains these API aggregation and data limits](https://developers.google.com/webmaster-tools/v1/searchanalytics/query).",
    "", "| Priority page | Clicks | Impressions | CTR | Avg position | First improvement |", "| --- | ---: | ---: | ---: | ---: | --- |"]
improve = {"/": "Clarify pad versus crop; demonstrate output and preserve mobile usability.", "/upscaler": "Deliver honest non-AI enlargement and verified PNG/alpha behavior.", "/image-size-calculator": "Calculate ratio, megapixels and proportional dimensions.", "/guides/instagram-reels-stories-guide": "Answer shared-size intent immediately; verify platform claims.", "/resize/linkedin": "Explain1200x627 and retain the chosen preset in the tool.", "/resize/instagram": "Offer configured sizing and explain display cropping."}
for p in S["pages"]:
    if p["path"] in improve:
        lines.append(f"| `{p['path']}` |{p['clicks']}|{p['impressions']:,}|{p['ctr']*100:.2f}%|{p['position']:.2f}|{improve[p['path']]}|")
lines += ["", "Home's382 clicks combine363 www and19 apex clicks by path, about83% of property clicks. Historical apex performance does not establish a current canonical failure. Mobile supplies319 clicks,69.2%, making phone usability a business priority. Upscaler's28 clicks are recent emergence; it had no impressions in the previous window. LinkedIn/Instagram and secondary platform topics have small samples.",
    "", "The most actionable homepage query leads are `square image`,2,309 impressions/10 clicks/position9.12, and `make image square`,1,003/3/7.72. Calculator's exact `image size calculator` query has138 impressions/2 clicks/9.09. Upscaler's `png upscaler` has42 impressions/0 clicks/3.74. These observations guide relevance work; they do not justify a forecast or a generic CTR target. `square pic` is ambiguous between brand and generic intent.",
    "", "See [full Google findings](findings/google.md), [page performance CSV](page-performance.csv), [query opportunities CSV](query-opportunities.csv), and [keyword/intent plan](KEYWORD-INTENT-PLAN.md).",
    "", "## Findings that change the order of work", "", "No critical sitewide crawl blocker was demonstrated. All49 canonical pages return200, expose text/headings in HTML, self-canonicalize and lack noindex. The main sitemap is valid, with49 submitted URLs and zero reported GSC errors. The largest risks are product reliability, intent mismatch and mobile experience.",
    "", "### High priority", "", "1. **Converter output does not always match the selected format.** Live AVIF and BMP jobs download PNG bytes with changed extensions. The TIFF test file fails two independent decoders. GIF interoperability also needs review, though Chromium accepts that export. A browser can silently fall back to PNG for unsupported Canvas output types; the product must detect that result or use an encoder. [MDN documents the fallback](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob).",
    "2. **Compressor settings can leave stale output.** A completed JPEG job can still download JPEG after selecting WebP and recompressing. Its target-size search also fires identical midpoint qualities before asynchronous results update the bounds. Exact-size and lossless-PNG claims exceed demonstrated behavior. Test targets, formats, dimensions and transparency together.",
    "3. **Narrow-screen layout and readability need repair.** At375px, the converter document overflows to523px and navigation clips. Home overflows to382px. Homepage H1 letter spacing is-2px at a17.6px font size, visibly compressing the heading. Third-party promotions occupy the top bar. Reserve space and measure their performance effect before making a widget decision.",
    "4. **Prepared fixes have not reached the public site.** The live image sitemap contains an unescaped ampersand at line104 and fails XML parsing, while the main sitemap remains valid. Live upscaler/calculator/guide copy and CSP still show older behavior. Several repairs are already in local diffs. Review/revalidate those changes and release them rather than writing a second version. [Google's image-sitemap specification](https://developers.google.com/search/docs/crawling-indexing/sitemaps/image-sitemaps) lists the supported tags.",
    "5. **Some product claims are inaccurate or unsupported.** Live upscaler copy promises specific bicubic/GPU/detail-recovery behavior not established by its Canvas smoothing/sharpening implementation. Crop mode cannot preserve the whole image as padding does. Platform tables mix square and non-square destinations and make broad no-crop promises. Correct copy and visible FAQs to match actual tools.",
    "6. **Crop downloads use display dimensions.** A 600 x 400 test image exports as 560 x 560 in the default mode and 700 x 394 in 16:9. The implementation derives output size from the display rectangle rather than the intended source region. Map coordinates and constrain bounds before promising full-resolution cropping. The same default size occurred on mobile, so this sample does not establish device-dependent output.",
    "", "### Medium priority", "", "- Platform resizer and conversion detail pages often act as instructions/CTAs rather than configured tools. Users must navigate elsewhere and reselect their task. Align title, first-screen action, tool state and schema.",
    "- Google reports `/cropper` as discovered, currently not indexed. Nine other sampled existing URLs are indexed with intended www canonicals. The pending new square guide is unknown to Google. This sample is not a49-page index count or evidence of a penalty.",
    "- `/converter/webp-to-avif` is sitemap-only in the observed raw-anchor graph. Link it contextually after AVIF export works.48 of49 sitemap pages are reachable within two anchor clicks.",
    "- All nine live guides lack original HTML image examples and clear linked official specification references. Add practical before/after/crop diagrams and dated primary citations on priority topics rather than expanding generic prose.",
    "- SevenOneLabs is described as a team/lab but typed both Person and Organization. Choose truthful authorship and a consistent entity ID.13 informational resizer pages use WebApplication despite no embedded tool on those URLs.",
    "-35 of49 pages lack `og:image`. The14 existing share PNGs are1200x630 and under51KB; the logo is valid. Reuse relevant assets. This improves sharing consistency, not a guaranteed ranking signal.",
    "- `llms.txt` says no tracking while the site loads analytics. Local image processing and anonymous/event analytics are different statements. Verify actual network behavior and align wording. Some analytics requests are blocked by live CSP, limiting measurement.",
    "", "### Low priority and informational findings", "", "31 HowTo blocks are obsolete for Google's rich results. Cleanup is optional during template work, with visible instructions preserved.23 FAQPage blocks do not create a Google FAQ rich-result opportunity; Google retired that feature on7 May2026. Existing FAQ markup is not a critical defect and should not be removed merely to improve a checklist. [Google's changelog records the retirement](https://developers.google.com/search/updates).",
    "", "No AggregateRating/Review markup was found. Do not invent reviews to make software-app validators pass. The existing entities can describe software without qualifying for a particular rich result. Long titles/descriptions warrant editing for relevance and clarity, but60/160 characters are audit heuristics, not fixed Google limits or indexing requirements. The author page repeats the brand suffix once unnecessarily.",
    "", "`llms.txt` lacks Markdown links. Optional formatting repair can help supporting tools, but it is not a Google ranking requirement. No measured AI citation lift, WebMCP conformance score or Lighthouse Agentic fraction is claimed. Google says [ordinary SEO applies to AI features](https://developers.google.com/search/docs/appearance/ai-features).",
    "", "## Performance evidence", "", "Lighthouse13.5.0, one fresh live homepage lab run per device. Results vary with server/network/browser/widget conditions; these are not a controlled regression against the old report.",
    "", "| Profile | Performance | LCP | TBT | CLS |", "| --- | ---: | ---: | ---: | ---: |", "| Mobile |64/100|3.96s|529ms|0.039|", "| Desktop |84/100|0.62s|173ms|0.212|",
    "", "Mobile LCP and desktop CLS need improvement against the usual thresholds. TBT is a laboratory blocking metric, not field INP. Both runs scored83 accessibility,73 best practices and100 automated SEO; those narrow automated checks do not cover tool correctness or search-intent quality. The desktop CLI reported a Windows cleanup error after writing its complete report; the JSON measurement is preserved.",
    "", "PSI returned quota429 and no CrUX API key was available. Field LCP/INP/CLS and a sitewide CWV pass/fail remain unknown. Repeat comparable lab runs after targeted performance changes and validate real-user data when available. [Web Vitals guidance](https://web.dev/articles/vitals) distinguishes field and lab measurement.",
    "", "## Score and confidence", "", "The seven category scores below are editorial judgments. A lower score prioritizes the observed weaknesses; it does not identify an algorithmic penalty. Performance is provisional because field data are missing. No separate tool-quality score is mixed into the weights; it contributes to content-quality assessment.",
    "", "| Category | Weight | Score | Basis |", "| --- | ---: | ---: | --- |"]
for c in categories:
    lines.append(f"| {c['name']} |{c['weight']}%|{c['score']}/100|{c['basis']}|")
lines += ["", "Confidence is high for fetched HTTP/XML/metadata, saved GSC responses and reproduced Chromium downloads. It is moderate for search-intent hypotheses and implementation-wide conclusions from representative tests. Field performance, conversion impact, full cross-browser support, backlink quality and AI citation visibility were not measured. Common Crawl's January-March2026 graph did not contain the domain; that does not establish zero backlinks.",
    "", "## Release sequence and what success means", "", "Fix and verify the actual tools and mobile paths, then review/release the prepared source changes. Improve the homepage and calculator/upscaler next, followed by configured platform flows and sourced guides. Expand content only when recurring demand and a functioning tool support it. Google's [helpful-content guidance](https://developers.google.com/search/docs/fundamentals/creating-helpful-content) includes functional tools as main content and rejects a preferred word count.",
    "", "The [action plan](ACTION-PLAN.md) gives each action its observation, dependency, acceptance test, failure condition and leading indicator. The first five practical wins are image-sitemap repair, honest upscaler copy, the prepared calculator functions, reused share previews and clearer homepage framing. Most are already partly prepared; all need public verification after deployment.",
    "", "Do not attribute this snapshot's traffic growth to unshipped changes. Record the deployment date and compare the same page/query cohorts after recrawl and28 complete post-release days. Track successful downloads as well as clicks. The next audit should verify real file formats, changed compressor settings, mobile overflow, live XML/copy/CSP, cropper indexing, and whether the priority query groups produce more successful tool use.",
    "", "## Evidence index", "", "- [Action plan](ACTION-PLAN.md) and [keyword/intent plan](KEYWORD-INTENT-PLAN.md)", "- [Technical](findings/technical.md), [sitemap](findings/sitemap.md), [schema](findings/schema.md), [images](findings/images.md)", "- [Content quality](findings/content.md), [search intent](findings/search-intent.md), [Google data](findings/google.md)", "- [Tool quality](findings/tool-quality.md), [performance](findings/performance.md), [visual/mobile](findings/visual.md), [AI/agent readiness](findings/geo-agentic.md)", "- [Structured audit envelope](audit-data.json), [crawl](data/crawl.json), [GSC manifest](data/gsc/manifest.json), [screenshots](screenshots/)",
    "", "A formatted PDF can be generated from `audit-data.json` with `/seo google report full`. This audit has not deployed changes or submitted indexing requests."]

# Preserve code identifiers, paths, links and action IDs while spacing prose.
import re
def prose_spacing(text):
    protected = r"(`[^`\n]*`|https?://[^\s)]+|\]\([^)]*\)|\b(?:A\d+|H[1-6]s?|GA4|HTML5|p75)\b)"
    parts = re.split(protected, text)
    for i in range(0, len(parts), 2):
        part = re.sub(r"(?<=[A-Za-z])(?=\d)", " ", parts[i])
        part = re.sub(r"(?<=\d)(?=[A-Za-z])", " ", part)
        part = re.sub(r"(?<=[,;])(?=[A-Za-z])", " ", part)
        part = re.sub(r"(?<=[A-Za-z%]),(?=\d)", ", ", part)
        part = re.sub(r"(?<=[A-Za-z])\.(?=\d)", ". ", part)
        part = re.sub(r"(?m)^-(?=\d)", "- ", part)
        part = part.replace("is-2", "is -2")
        parts[i] = part
    return "".join(parts).replace("`,2,309", "`, 2,309").replace("`,1,003", "`, 1,003")
body = prose_spacing("\n".join(lines) + "\n")
(ROOT / "FULL-AUDIT-REPORT.md").write_text(body, encoding="utf-8")

plan = ["# SquarePic prioritized action plan", "", "8 October 2026. Audit only. Existing source fixes have not been assumed deployed. No confirmed critical sitewide indexing blocker was found. High priority actions address live tool reliability, mobile task completion and the release gap.",
        "", "Dependency sequence: A1/A2/A3/A12 → reviewed release A4 → A5/A6/A7 → A8/A9/A10, with measurement A11 prepared during release. Do not wait for a28-day SEO comparison to fix a known corrupt/mislabeled download. Effort estimates are indicative and exclude Google recrawl latency."]
for a in actions:
    plan += ["", f"## {a['id']} · {a['priority']} · {a['title']}", "",
             "Observation: " + a["observation"], "", "Action: " + a["recommendation"], "",
             "Dependency: " + a["depends_on"], "", "Acceptance: " + a["acceptance"], "",
             "Failed if: " + a["failed_if"], "", "Leading indicator: " + a["indicator"], "",
             "Estimated effort: " + a["effort"] + "."]
plan += ["", "## Low-priority maintenance", "", "Clean the duplicated author-title suffix, direct redirecting links to their actual configured destination, optionally simplify obsolete HowTo markup, and improve optional llms Markdown formatting. Preserve helpful FAQs. Missing WebMCP/agent catalogs, FAQ rich-result markup, arbitrary word counts and wholesale image-format replacement are not growth priorities.",
         "", "## Measurement window", "", "Capture deployment/commit, verify public output, then inspect after recrawl. Compare the same query groups across28 complete post-release days and the saved baseline, split by device and important market when samples allow. Track successful tool exports, not just visits. If clicks rise while success falls, the release has not achieved the intended result."]
(ROOT / "ACTION-PLAN.md").write_text(prose_spacing("\n".join(plan) + "\n"), encoding="utf-8")
print(f"Wrote full report, action plan and audit envelope; provisional score {score}/100")
